version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - davidleger95
  ignore:
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: babel-plugin-styled-components
    versions:
    - 1.10.7
